version: "3.8"

services:
  updater:
    container_name: updater
    build:
      context: .
      dockerfile: Dockerfile_updater
    entrypoint: ["sh", "-c", "while true; do sleep 60; python -u /app/update_app.py; done"]
    environment:
      - TOKENS=ETH:ethereum,BTC:bitcoin,SOL:solana
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - DATABASE_PATH=/app/data/prices.db
      - CGC_API_KEY=CG-MuKoMVL1JZ8Mv4BhcMYPEF6M
    volumes:
      - ./source-data:/app/data
    restart: unless-stopped

  source-01:
    container_name: source-01
    build: .    
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8001
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKENS=ETH:ethereum,BTC:bitcoin,SOL:solana
      - INTERVAL_STEPS=10
      - LOOK_BACK=10
      - PREDICTION_STEPS=10
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "python init_data.py && gunicorn --preload --bind 0.0.0.0:8001 --log-level info --error-logfile - --access-logfile - 
      --worker-tmp-dir /dev/shm --graceful-timeout 120 --timeout 30 --keep-alive 5 
      --worker-class gthread --workers 4 --threads 8 app:app"
    volumes:
      - ./source-data:/app/data
      - ./models:/app/models
    restart: unless-stopped

  source-02:
    container_name: source-02
    build: .
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8002
      - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet.allora.network/
      - TOKENS=ETH:ethereum,BNB:binancecoin,ARB:arbitrum
      - INTERVAL_STEPS=20
      - LOOK_BACK=10
      - PREDICTION_STEPS=20
    ports:
      - "8002:8002"  # Changed to a unique port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "python init_data.py && gunicorn --preload --bind 0.0.0.0:8002 --log-level info --error-logfile - --access-logfile - 
      --worker-tmp-dir /dev/shm --graceful-timeout 120 --timeout 30 --keep-alive 5 
      --worker-class gthread --workers 4 --threads 8 app:app"  # Changed to bind to port 8002
    volumes:
      - ./source-data:/app/data
      - ./models:/app/models
    restart: unless-stopped

  allora-worker-1:
    container_name: allora-worker-1
    image: alloranetwork/allora-offchain-node:v0.5.1
    volumes:
      - ./worker-data:/data
    depends_on:
      source-01:
        condition: service_healthy
      source-02:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file
    restart: unless-stopped
